name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "94e51929-350c-4a62-b198-0772d8a3110d"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "3a4f4cbc154f4f77ae9da46a052400e6"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
